# Generated by Django 2.2 on 2019-07-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='context',
            field=models.TextField(max_length=300, verbose_name='Текст'),
        ),
    ]
