# Generated by Django 2.2 on 2019-07-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190716_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='context',
            field=models.TextField(max_length=200, verbose_name='Текст'),
        ),
    ]
